export enum STATUS {
  PENDING = 'pending',
  ACCEPTED = 'accepted',
  REJECTED = 'rejected',
}
export enum CONSULTATION_TYPE {
  VIDEOCALL = 'VIDEOCALL',
  VIDEOCALLWITHMEDICINE = 'VIDEOCALLWITHMEDICINE',
  PRESCRIPTION = 'PRESCRIPTION',
  PRESCRIPTIONWITHMEDICINE = 'PRESCRIPTIONWITHMEDICINE',
}
